### ISSUE TITLE
在 chromebook 上使用出现报错

### ISSUE THREAD

**Issue by fish1968** [fish1968/bb_download_with_selenium#6]
```
Traceback (most recent call last):
  File "/home/username/github/bb_download_with_selenium/main.py", line 37, in <module>
    driver = webdriver.Chrome("./chromedriver", options=options)
  File "/home/yabin/miniconda3/envs/bb_download/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/username/miniconda3/envs/bb_download/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/username/miniconda3/envs/bb_download/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127

```
![image](https://user-images.githubusercontent.com/62780813/226536131-b171acf2-8a20-46d8-b54b-53d25305722e.png)

**Comment by fish1968** [comment]
我有两台 Chromebook，一台是新配置的环境，失效，但是另一台的工作非常完美。
